### PR TITLE
Profile CRUD functionality is now fully working

### PR DESCRIPTION
**Pull request by Djescho**
On this branch i've created the register form, profile page and the profile edit form.

### CODE REVIEW

**Review by jody29 — CHANGES_REQUESTED** [review]
API key is visible and should be in a .env file

**Review by basv1996 — CHANGES_REQUESTED** [review]
I agree with the comments Jody made. Put the API in a .env file.

**Review by jody29 — APPROVED** [review]
API key is changed to .env, thanks

**Review by basv1996 — APPROVED** [review]
Lekker bezig

**Review by Sophievanderburg — APPROVED** [review]
Nice work Djescho!! I see you did the requested changes, so that is great!

**Pull request merged**
